export const thyEditorConstant = {
    typeArray: {
        hs: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'],
        simple: ['bold', 'italic', 'link', 'uploadImg', 'divider', 'hr', 'quote', 'list', 'list-2', 'table'],
        complex: ['heading', 'bold', 'italic', 'underline',
            'strikethrough', 'divider', 'hr', 'quote', 'list', 'list-2', 'square', 'check-square', 'divider',
            'link', 'image', 'code', 'table', 'divider', 'math', 'diagram', 'gantt', 'divider', 'preview'],
        all: ['heading', 'bold', 'italic', 'underline',
            'strikethrough', 'divider', 'hr', 'quote', 'list', 'list-2',
            'square', 'check-square', 'divider', 'link', 'uploadImg',
            'code', 'table', 'divider', 'math', 'diagram', 'gantt', 'divider', 'preview']
    },
    allButtons: {
        'heading': {
            id: 0,
            title: '标题',
            className: 'wtf wtf-heading',
            type: 'headingFns',
            name: 'heading'
        },
        'bold': {
            id: 1,
            title: '粗体',
            className: 'wtf wtf-bold',
            modifier: '**',
            type: 'styleFn',
            name: 'bold'
        },
        'italic': {
            id: 2,
            title: '斜体',
            className: 'wtf wtf-italic',
            modifier: '*',
            type: 'styleFn',
            name: 'italic'
        },
        'underline': {
            id: 3,
            title: '下划线',
            className: 'wtf wtf-underline',
            modifier: 'u',
            type: 'styleFn',
            name: 'underline'
        },
        'strikethrough': {
            id: 4,
            title: '删除线',
            className: 'wtf wtf-strikethrough',
            modifier: '~~',
            type: 'styleFn',
            name: 'strikethrough'
        },
        'h1': {
            id: 5,
            title: '标题 1',
            className: 'h1',
            level: '1',
            type: 'headingFn',
            name: 'h1'
        },
        'h2': {
            id: 6,
            title: '标题 2',
            className: 'h2',
            level: '2',
            type: 'headingFn',
            name: 'h2'
        },
        'h3': {
            id: 7,
            title: '标题 3',
            className: 'h3',
            level: '3',
            type: 'headingFn',
            name: 'h3'
        },
        'h4': {
            id: 8,
            title: '标题 4',
            className: 'h4',
            level: '4',
            type: 'headingFn',
            name: 'h4'
        },
        'h5': {
            id: 9,
            title: '标题 5',
            className: 'h5',
            level: '5',
            type: 'headingFn',
            name: 'h5'
        },
        'h6': {
            id: 10,
            title: '标题 6',
            className: 'h6',
            level: '6',
            type: 'headingFn',
            name: 'h6'
        },
        'hr': {
            id: 11,
            title: '横线',
            className: 'wtf wtf-minus',
            type: 'styleFn',
            name: 'hr'
        },
        'quote': {
            id: 12,
            title: '引用',
            className: 'wtf wtf-quote-left',
            prefix: '> ',
            type: 'styleFn',
            name: 'quote'
        },
        'list': {
            id: 13,
            title: '无序列表',
            className: 'wtf wtf-list-ul',
            prefix: '- ',
            type: 'styleFn',
            name: 'list'
        },
        'list-2': {
            id: 14,
            title: '有序列表',
            className: 'wtf wtf-list-ol',
            prefix: '1. ',
            type: 'styleFn',
            name: 'list-2'
        },
        'square': {
            id: 15,
            title: '未完成任务列表',
            className: 'wtf wtf-square',
            prefix: '- [ ] ',
            type: 'styleFn',
            name: 'square'
        },
        'check-square': {
            id: 16,
            title: '已完成任务列表',
            className: 'wtf wtf-check-square-o',
            prefix: '- [x] ',
            type: 'styleFn',
            name: 'check-square'
        },
        'link': {
            id: 17,
            title: '链接',
            className: 'wtf wtf-link',
            text: '链接文字',
            url: 'http://example.com',
            type: 'styleFn',
            name: 'link'
        },
        'image': {
            id: 18,
            title: '图片',
            className: 'wtf wtf-image',
            text: '图片描述',
            url: 'http://example.com/example.png',
            type: 'styleFn',
            name: 'image'
        },
        'code': {
            id: 19,
            title: '代码',
            className: 'wtf wtf-code',
            type: 'styleFn',
            name: 'code'
        },
        'table': {
            id: 20,
            title: '表格',
            className: 'wtf wtf-table-toolbar',
            type: 'tableFn',
            name: 'table'
        },
        'emoji': {
            id: 21,
            title: 'Emoji 图标',
            className: 'wtf wtf-smile-o',
            target: 'emoji-modal',
            type: 'emoji'
        },
        'math': {
            id: 22,
            title: '数学公式',
            className: 'wtf wtf-superscript',
            sample: 'E = mc^2',
            type: 'mathFn',
            name: 'math'
        },
        'diagram': {
            id: 24,
            title: '顺序图',
            className: 'wtf wtf-exchange-alt',
            type: 'diagram',
            name: 'diagram'
        },
        'gantt': {
            id: 25,
            title: '甘特图',
            className: 'wtf wtf-sliders-h',
            type: 'gantt',
            name: 'gantt'
        },
        'preview': {
            id: 27,
            title: '预览',
            className: 'wtf wtf-columns',
            type: 'preview'
        },
        'expand': {
            id: 28,
            title: '最大化',
            title2: '还原',
            className: 'wtf wtf-expand',
            type: 'expand'
        },
        'divider': {
            id: parseInt(Math.random() * 1000000 + '', 10),
            type: 'divider'
        },
        'uploadImg': {
            id: 29,
            title: '上传',
            className: 'wtf wtf-image',
            text: '上传',
            type: 'uploadImg',
            name: 'image'
        },
        'linkModule': {
            id: 30,
            title: '关联',
            className: 'wtf wtf-link-entity',
            text: '关联',
            type: 'linkModule',
            name: 'linkModule'
        },
    },
    tableMenu: [
        [
            [0, 0],
            [0, 1],
            [0, 2],
            [0, 3],
            [0, 4],
            [0, 5]
        ],
        [
            [1, 0],
            [1, 1],
            [1, 2],
            [1, 3],
            [1, 4],
            [1, 5]
        ],
        [
            [2, 0],
            [2, 1],
            [2, 2],
            [2, 3],
            [2, 4],
            [2, 5]
        ],
        [
            [3, 0],
            [3, 1],
            [3, 2],
            [3, 3],
            [3, 4],
            [3, 5]
        ],
        [
            [4, 0],
            [4, 1],
            [4, 2],
            [4, 3],
            [4, 4],
            [4, 5]
        ]
    ],
    language: {
        'en-us': {
            'heading': 'H1',
            'bold': 'Bold',
            'italic': 'Italic',
            'underline': 'Underline',
            'strikethrough': 'Strike through',
            'h1': 'H1',
            'h2': 'H2',
            'h3': 'H3',
            'h4': 'H4',
            'h5': 'H5',
            'h6': 'H6',
            'hr': 'Hr',
            'quote': 'Quote',
            'list': 'Ul',
            'list-2': 'Ol',
            'square': 'Unfinished',
            'check-square': 'Completed',
            'link': 'Link',
            'link-text': 'Link',
            'image': 'Image',
            'image-text': 'Description',
            'code': 'Code',
            'table': 'Table',
            'emoji': 'Emoji',
            'math': 'Math',
            'flow': 'Flow',
            // 'diagram': 'Flowchart',
            'gantt': 'Gantt',
            'preview': 'Preview',
            'max': 'Max',
            'original': 'Reduction',
            'col': 'col',
            'row': 'row',
            'diagram': 'sequenceDiagram\nA->>B: How are you?\nB->>A: I am fine!',
            'placeholder': 'Content ...'
        },
        'zh-cn': {
            'heading': '标题',
            'bold': '粗体',
            'italic': '斜体',
            'underline': '下划线',
            'strikethrough': '删除线',
            'h1': '标题 1',
            'h2': '标题 2',
            'h3': '标题 3',
            'h4': '标题 4',
            'h5': '标题 5',
            'h6': '标题 6',
            'hr': '横线',
            'quote': '引用',
            'list': '无序列表',
            'list-2': '有序列表',
            'square': '未完成任务列表',
            'check-square': '已完成任务列表',
            'link': '链接',
            'link-text': '链接文字',
            'image': '图片',
            'image-text': '图片描述',
            'code': '代码',
            'table': '表格',
            'emoji': 'Emoji 图标',
            'math': '数学公式',
            'flow': '流程图',
            // 'diagram': '顺序图',
            'gantt': '甘特图',
            'preview': '预览',
            'max': '最大化',
            'original': '还原',
            'col': '列',
            'row': '行',
            'diagram': 'sequenceDiagram\nA->>B: 你好吗?\nB->>A: 我很好3!',
            'placeholder': '输入内容...'
        },
        'zh-tw': {
            'heading': '標題',
            'bold': '粗體',
            'italic': '斜體',
            'underline': '下劃線',
            'strikethrough': '刪除線',
            'h1': '標題 1',
            'h2': '標題 2',
            'h3': '標題 3',
            'h4': '標題 4',
            'h5': '標題 5',
            'h6': '標題 6',
            'hr': '橫線',
            'quote': '引用',
            'list': '無序列表',
            'list-2': '有序列表',
            'square': '未完成任務列表',
            'check-square': '已完成任務列表',
            'link': '鏈接',
            'link-text': '鏈接文字',
            'image': '圖片',
            'image-text': '圖片描述',
            'code': '代碼',
            'table': '表格',
            'emoji': 'Emoji 圖標',
            'math': '數學公式',
            'flow': '流程圖',
            // 'diagram': '順序圖',
            'gantt': '甘特圖',
            'preview': '預覽',
            'max': '最大化',
            'original': '還原',
            'col': '列',
            'row': '行',
            'diagram': 'sequenceDiagram\nA->>B: 你好嗎?\nB->>A: 我很好!',
            'placeholder': '輸入內容...'
        },
        'ja-jp': {
            'heading': '标题',
            'bold': '粗体',
            'italic': '斜体',
            'underline': '下划线',
            'strikethrough': '删除线',
            'h1': '标题 1',
            'h2': '标题 2',
            'h3': '标题 3',
            'h4': '标题 4',
            'h5': '标题 5',
            'h6': '标题 6',
            'hr': '横线',
            'quote': '引用',
            'list': '无序列表',
            'list-2': '有序列表',
            'square': '未完成任务列表',
            'check-square': '已完成任务列表',
            'link': '链接',
            'link-text': '链接文字',
            'image': '图片',
            'image-text': '图片描述',
            'code': '代码',
            'table': '表格',
            'emoji': 'Emoji 图标',
            'math': '数学公式',
            'flow': '流程图',
            // 'diagram': '顺序图',
            'gantt': '甘特图',
            'preview': '预览',
            'max': '最大化',
            'original': '还原',
            'col': '列',
            'row': '行',
            'diagram': 'sequenceDiagram\nA->>B: 你好吗?\nB->>A: 我很好3!',
            'placeholder': '输入内容...'
        }
    },
    emojis: [
        { name: 'bowtie', unicode: '' },
        { name: 'smile', unicode: '1F604' },
        { name: 'laughing', unicode: '1F606' },
        { name: 'blush', unicode: '1F60A' },
        { name: 'smiley', unicode: '1F603' },
        { name: 'relaxed', unicode: '263A' },
        { name: 'smirk', unicode: '1F60F' },
        { name: 'heart_eyes', unicode: '1F60D' },
        { name: 'kissing_heart', unicode: '1F618' },
        { name: 'kissing_closed_eyes', unicode: '1F61A' },
        { name: 'flushed', unicode: '1F633' },
        { name: 'relieved', unicode: '1F60C' },
        { name: 'satisfied', unicode: '' },
        { name: 'grin', unicode: '1F601' },
        { name: 'wink', unicode: '1F609' },
        { name: 'stuck_out_tongue_winking_eye', unicode: '1F61C' },
        { name: 'stuck_out_tongue_closed_eyes', unicode: '1F61D' },
        { name: 'grinning', unicode: '1F600' },
        { name: 'kissing', unicode: '1F617' },
        { name: 'kissing_smiling_eyes', unicode: '1F619' },
        { name: 'stuck_out_tongue', unicode: '1F61B' },
        { name: 'sleeping', unicode: '1F634' },
        { name: 'worried', unicode: '1F61F' },
        { name: 'frowning', unicode: '1F626' },
        { name: 'anguished', unicode: '1F627' },
        { name: 'open_mouth', unicode: '1F62E' },
        { name: 'grimacing', unicode: '1F62C' },
        { name: 'confused', unicode: '1F615' },
        { name: 'hushed', unicode: '1F62F' },
        { name: 'expressionless', unicode: '1F611' },
        { name: 'unamused', unicode: '1F612' },
        { name: 'sweat_smile', unicode: '1F605' },
        { name: 'sweat', unicode: '1F613' },
        { name: 'weary', unicode: '1F629' },
        { name: 'pensive', unicode: '1F614' },
        { name: 'disappointed', unicode: '1F61E' },
        { name: 'confounded', unicode: '1F616' },
        { name: 'fearful', unicode: '1F628' },
        { name: 'cold_sweat', unicode: '1F630' },
        { name: 'persevere', unicode: '1F623' },
        { name: 'joy', unicode: '1F602' },
        { name: 'astonished', unicode: '1F632' },
        { name: 'scream', unicode: '1F631' },
        { name: 'neckbeard', unicode: '' },
        { name: 'tired_face', unicode: '1F62B' },
        { name: 'angry', unicode: '1F620' },
        { name: 'rage', unicode: '1F621' },
        { name: 'triumph', unicode: '1F624' },
        { name: 'sleepy', unicode: '1F62A' },
        { name: 'yum', unicode: '1F60B' },
        { name: 'mask', unicode: '1F637' },
        { name: 'sunglasses', unicode: '1F60E' },
        { name: 'dizzy_face', unicode: '1F635' },
        { name: 'imp', unicode: '1F47F' },
        { name: 'smiling_imp', unicode: '1F608' },
        { name: 'neutral_face', unicode: '1F610' },
        { name: 'no_mouth', unicode: '1F636' },
        { name: 'innocent', unicode: '1F607' },
        { name: 'alien', unicode: '1F47D' },
        { name: 'yellow_heart', unicode: '1F49B' },
        { name: 'blue_heart', unicode: '1F499' },
        { name: 'purple_heart', unicode: '1F49C' },
        { name: 'heart', unicode: '2764' },
        { name: 'green_heart', unicode: '1F49A' },
        { name: 'broken_heart', unicode: '1F494' },
        { name: 'heartbeat', unicode: '1F493' },
        { name: 'heartpulse', unicode: '1F497' },
        { name: 'two_hearts', unicode: '1F495' },
        { name: 'revolving_hearts', unicode: '1F49E' },
        { name: 'cupid', unicode: '1F498' },
        { name: 'sparkling_heart', unicode: '1F496' },
        { name: 'sparkles', unicode: '2728' },
        { name: 'star', unicode: '2B50' },
        { name: 'star2', unicode: '1F31F' },
        { name: 'dizzy', unicode: '1F4AB' },
        { name: 'boom', unicode: '1F4A5' },
        { name: 'collision', unicode: '' },
        { name: 'anger', unicode: '1F4A2' },
        { name: 'exclamation', unicode: '2757' },
        { name: 'question', unicode: '2753' },
        { name: 'grey_exclamation', unicode: '2755' },
        { name: 'grey_question', unicode: '2754' },
        { name: 'zzz', unicode: '1F4A4' },
        { name: 'dash', unicode: '1F4A8' },
        { name: 'sweat_drops', unicode: '1F4A6' },
        { name: 'notes', unicode: '1F3B6' },
        { name: 'musical_note', unicode: '1F3B5' },
        { name: 'fire', unicode: '1F525' },
        { name: 'hankey', unicode: '' },
        { name: 'poop', unicode: '1F4A9' },
        { name: 'shit', unicode: '' },
        { name: '+1', unicode: '' },
        { name: 'thumbsup', unicode: '1F44D' },
        { name: '-1', unicode: '' },
        { name: 'thumbsdown', unicode: '1F44E' },
        { name: 'ok_hand', unicode: '1F44C' },
        { name: 'punch', unicode: '1F44A' },
        { name: 'facepunch', unicode: '' },
        { name: 'fist', unicode: '270A' },
        { name: 'v', unicode: '270C' },
        { name: 'wave', unicode: '1F44B' },
        { name: 'hand', unicode: '' },
        { name: 'raised_hand', unicode: '270B' },
        { name: 'open_hands', unicode: '1F450' },
        { name: 'point_up', unicode: '261D' },
        { name: 'point_down', unicode: '1F447' },
        { name: 'point_left', unicode: '1F448' },
        { name: 'point_right', unicode: '1F449' },
        { name: 'raised_hands', unicode: '1F64C' },
        { name: 'pray', unicode: '1F64F' },
        { name: 'point_up_2', unicode: '1F446' },
        { name: 'clap', unicode: '1F44F' },
        { name: 'muscle', unicode: '1F4AA' },
        { name: 'metal', unicode: '' },
        { name: 'walking', unicode: '1F6B6' },
        { name: 'runner', unicode: '1F3C3' },
        { name: 'running', unicode: '' },
        { name: 'couple', unicode: '1F46B' },
        { name: 'family', unicode: '1F46A' },
        { name: 'two_men_holding_hands', unicode: '1F46C' },
        { name: 'two_women_holding_hands', unicode: '1F46D' },
        { name: 'ok_woman', unicode: '1F646' },
        { name: 'no_good', unicode: '1F645' },
        { name: 'information_desk_person', unicode: '1F481' },
        { name: 'bride_with_veil', unicode: '1F470' },
        { name: 'person_with_pouting_face', unicode: '1F64E' },
        { name: 'person_frowning', unicode: '1F64D' },
        { name: 'bow', unicode: '1F647' },
        { name: 'couplekiss', unicode: '1F48F' },
        { name: 'couple_with_heart', unicode: '1F491' },
        { name: 'massage', unicode: '1F486' },
        { name: 'haircut', unicode: '1F487' },
        { name: 'nail_care', unicode: '1F485' },
        { name: 'boy', unicode: '1F466' },
        { name: 'girl', unicode: '1F467' },
        { name: 'woman', unicode: '1F469' },
        { name: 'man', unicode: '1F468' },
        { name: 'baby', unicode: '1F476' },
        { name: 'older_woman', unicode: '1F475' },
        { name: 'older_man', unicode: '1F474' },
        { name: 'person_with_blond_hair', unicode: '1F471' },
        { name: 'man_with_gua_pi_mao', unicode: '1F472' },
        { name: 'man_with_turban', unicode: '1F473' },
        { name: 'construction_worker', unicode: '1F477' },
        { name: 'cop', unicode: '1F46E' },
        { name: 'angel', unicode: '1F47C' },
        { name: 'princess', unicode: '1F478' },
        { name: 'smiley_cat', unicode: '1F63A' },
        { name: 'smile_cat', unicode: '1F638' },
        { name: 'heart_eyes_cat', unicode: '1F63B' },
        { name: 'kissing_cat', unicode: '1F63D' },
        { name: 'smirk_cat', unicode: '1F63C' },
        { name: 'scream_cat', unicode: '1F640' },
        { name: 'crying_cat_face', unicode: '1F63F' },
        { name: 'joy_cat', unicode: '1F639' },
        { name: 'pouting_cat', unicode: '1F63E' },
        { name: 'japanese_ogre', unicode: '1F479' },
        { name: 'japanese_goblin', unicode: '1F47A' },
        { name: 'see_no_evil', unicode: '1F648' },
        { name: 'hear_no_evil', unicode: '1F649' },
        { name: 'speak_no_evil', unicode: '1F64A' },
        { name: 'guardsman', unicode: '1F482' },
        { name: 'skull', unicode: '1F480' },
        { name: 'feet', unicode: '1F43E' },
        { name: 'lips', unicode: '1F444' },
        { name: 'kiss', unicode: '1F48B' },
        { name: 'droplet', unicode: '1F4A7' },
        { name: 'ear', unicode: '1F442' },
        { name: 'eyes', unicode: '1F440' },
        { name: 'nose', unicode: '1F443' },
        { name: 'tongue', unicode: '1F445' },
        { name: 'love_letter', unicode: '1F48C' },
        { name: 'bust_in_silhouette', unicode: '1F464' },
        { name: 'busts_in_silhouette', unicode: '1F465' },
        { name: 'speech_balloon', unicode: '1F4AC' },
        { name: 'thought_balloon', unicode: '1F4AD' },
        { name: 'feelsgood', unicode: '' },
        { name: 'finnadie', unicode: '' },
        { name: 'goberserk', unicode: '' },
        { name: 'godmode', unicode: '' },
        { name: 'hurtrealbad', unicode: '' },
        { name: 'rage1', unicode: '' },
        { name: 'rage2', unicode: '' },
        { name: 'rage3', unicode: '' },
        { name: 'rage4', unicode: '' },
        { name: 'suspect', unicode: '' },
        { name: 'trollface', unicode: '' },
        { name: 'sunny', unicode: '2600' },
        { name: 'umbrella', unicode: '2614' },
        { name: 'cloud', unicode: '2601' },
        { name: 'snowflake', unicode: '2744' },
        { name: 'snowman', unicode: '26C4' },
        { name: 'zap', unicode: '26A1' },
        { name: 'cyclone', unicode: '1F300' },
        { name: 'foggy', unicode: '1F301' },
        { name: 'ocean', unicode: '1F30A' },
        { name: 'cat', unicode: '1F431' },
        { name: 'dog', unicode: '1F436' },
        { name: 'mouse', unicode: '1F42D' },
        { name: 'hamster', unicode: '1F439' },
        { name: 'rabbit', unicode: '1F430' },
        { name: 'wolf', unicode: '1F43A' },
        { name: 'frog', unicode: '1F438' },
        { name: 'tiger', unicode: '1F42F' },
        { name: 'koala', unicode: '1F428' },
        { name: 'bear', unicode: '1F43B' },
        { name: 'pig', unicode: '1F437' },
        { name: 'pig_nose', unicode: '1F43D' },
        { name: 'cow', unicode: '1F42E' },
        { name: 'boar', unicode: '1F417' },
        { name: 'monkey_face', unicode: '1F435' },
        { name: 'monkey', unicode: '1F412' },
        { name: 'horse', unicode: '1F434' },
        { name: 'racehorse', unicode: '1F40E' },
        { name: 'camel', unicode: '1F42B' },
        { name: 'sheep', unicode: '1F411' },
        { name: 'elephant', unicode: '1F418' },
        { name: 'panda_face', unicode: '1F43C' },
        { name: 'snake', unicode: '1F40D' },
        { name: 'bird', unicode: '1F426' },
        { name: 'baby_chick', unicode: '1F424' },
        { name: 'hatched_chick', unicode: '1F425' },
        { name: 'hatching_chick', unicode: '1F423' },
        { name: 'chicken', unicode: '1F414' },
        { name: 'penguin', unicode: '1F427' },
        { name: 'turtle', unicode: '1F422' },
        { name: 'bug', unicode: '1F41B' },
        { name: 'honeybee', unicode: '' },
        { name: 'ant', unicode: '1F41C' },
        { name: 'beetle', unicode: '1F41E' },
        { name: 'snail', unicode: '1F40C' },
        { name: 'octopus', unicode: '1F419' },
        { name: 'tropical_fish', unicode: '1F420' },
        { name: 'fish', unicode: '1F41F' },
        { name: 'whale', unicode: '1F433' },
        { name: 'whale2', unicode: '1F40B' },
        { name: 'dolphin', unicode: '1F42C' },
        { name: 'cow2', unicode: '1F404' },
        { name: 'ram', unicode: '1F40F' },
        { name: 'rat', unicode: '1F400' },
        { name: 'water_buffalo', unicode: '1F403' },
        { name: 'tiger2', unicode: '1F405' },
        { name: 'rabbit2', unicode: '1F407' },
        { name: 'dragon', unicode: '1F409' },
        { name: 'goat', unicode: '1F410' },
        { name: 'rooster', unicode: '1F413' },
        { name: 'dog2', unicode: '1F415' },
        { name: 'pig2', unicode: '1F416' },
        { name: 'mouse2', unicode: '1F401' },
        { name: 'ox', unicode: '1F402' },
        { name: 'dragon_face', unicode: '1F432' },
        { name: 'blowfish', unicode: '1F421' },
        { name: 'crocodile', unicode: '1F40A' },
        { name: 'dromedary_camel', unicode: '1F42A' },
        { name: 'leopard', unicode: '1F406' },
        { name: 'cat2', unicode: '1F408' },
        { name: 'poodle', unicode: '1F429' },
        { name: 'paw_prints', unicode: '' },
        { name: 'bouquet', unicode: '1F490' },
        { name: 'cherry_blossom', unicode: '1F338' },
        { name: 'tulip', unicode: '1F337' },
        { name: 'four_leaf_clover', unicode: '1F340' },
        { name: 'rose', unicode: '1F339' },
        { name: 'sunflower', unicode: '1F33B' },
        { name: 'hibiscus', unicode: '1F33A' },
        { name: 'maple_leaf', unicode: '1F341' },
        { name: 'leaves', unicode: '1F343' },
        { name: 'fallen_leaf', unicode: '1F342' },
        { name: 'herb', unicode: '1F33F' },
        { name: 'mushroom', unicode: '1F344' },
        { name: 'cactus', unicode: '1F335' },
        { name: 'palm_tree', unicode: '1F334' },
        { name: 'evergreen_tree', unicode: '1F332' },
        { name: 'deciduous_tree', unicode: '1F333' },
        { name: 'chestnut', unicode: '1F330' },
        { name: 'seedling', unicode: '1F331' },
        { name: 'blossom', unicode: '1F33C' },
        { name: 'ear_of_rice', unicode: '1F33E' },
        { name: 'shell', unicode: '1F41A' },
        { name: 'globe_with_meridians', unicode: '1F310' },
        { name: 'sun_with_face', unicode: '1F31E' },
        { name: 'full_moon_with_face', unicode: '1F31D' },
        { name: 'new_moon_with_face', unicode: '1F31A' },
        { name: 'new_moon', unicode: '1F311' },
        { name: 'waxing_crescent_moon', unicode: '1F312' },
        { name: 'first_quarter_moon', unicode: '1F313' },
        { name: 'waxing_gibbous_moon', unicode: '1F314' },
        { name: 'full_moon', unicode: '1F315' },
        { name: 'waning_gibbous_moon', unicode: '1F316' },
        { name: 'last_quarter_moon', unicode: '1F317' },
        { name: 'waning_crescent_moon', unicode: '1F318' },
        { name: 'last_quarter_moon_with_face', unicode: '1F31C' },
        { name: 'first_quarter_moon_with_face', unicode: '1F31B' },
        { name: 'moon', unicode: '' },
        { name: 'earth_africa', unicode: '1F30D' },
        { name: 'earth_americas', unicode: '1F30E' },
        { name: 'earth_asia', unicode: '1F30F' },
        { name: 'volcano', unicode: '1F30B' },
        { name: 'milky_way', unicode: '1F30C' },
        { name: 'partly_sunny', unicode: '26C5' },
        { name: 'octocat', unicode: '' },
        { name: 'squirrel', unicode: '' },
        { name: 'bamboo', unicode: '1F38D' },
        { name: 'gift_heart', unicode: '1F49D' },
        { name: 'dolls', unicode: '1F38E' },
        { name: 'school_satchel', unicode: '1F392' },
        { name: 'mortar_board', unicode: '1F393' },
        { name: 'flags', unicode: '1F38F' },
        { name: 'fireworks', unicode: '1F386' },
        { name: 'sparkler', unicode: '1F387' },
        { name: 'wind_chime', unicode: '1F390' },
        { name: 'rice_scene', unicode: '1F391' },
        { name: 'jack_o_lantern', unicode: '1F383' },
        { name: 'ghost', unicode: '1F47B' },
        { name: 'santa', unicode: '1F385' },
        { name: 'christmas_tree', unicode: '1F384' },
        { name: 'gift', unicode: '1F381' },
        { name: 'bell', unicode: '1F514' },
        { name: 'no_bell', unicode: '1F515' },
        { name: 'tanabata_tree', unicode: '1F38B' },
        { name: 'tada', unicode: '1F389' },
        { name: 'confetti_ball', unicode: '1F38A' },
        { name: 'balloon', unicode: '1F388' },
        { name: 'crystal_ball', unicode: '1F52E' },
        { name: 'cd', unicode: '1F1E8-1F1E9' },
        { name: 'dvd', unicode: '1F4C0' },
        { name: 'floppy_disk', unicode: '1F4BE' },
        { name: 'camera', unicode: '1F4F7' },
        { name: 'video_camera', unicode: '1F4F9' },
        { name: 'movie_camera', unicode: '1F3A5' },
        { name: 'computer', unicode: '1F4BB' },
        { name: 'tv', unicode: '1F1F9-1F1FB' },
        { name: 'iphone', unicode: '1F4F1' },
        { name: 'phone', unicode: '' },
        { name: 'telephone', unicode: '260E' },
        { name: 'telephone_receiver', unicode: '1F4DE' },
        { name: 'pager', unicode: '1F4DF' },
        { name: 'fax', unicode: '1F4E0' },
        { name: 'minidisc', unicode: '1F4BD' },
        { name: 'vhs', unicode: '1F4FC' },
        { name: 'sound', unicode: '1F509' },
        { name: 'speaker', unicode: '1F508' },
        { name: 'mute', unicode: '1F507' },
        { name: 'loudspeaker', unicode: '1F4E2' },
        { name: 'mega', unicode: '1F4E3' },
        { name: 'hourglass', unicode: '231B' },
        { name: 'hourglass_flowing_sand', unicode: '23F3' },
        { name: 'alarm_clock', unicode: '23F0' },
        { name: 'watch', unicode: '231A' },
        { name: 'radio', unicode: '1F4FB' },
        { name: 'satellite', unicode: '1F4E1' },
        { name: 'loop', unicode: '27BF' },
        { name: 'mag', unicode: '1F50D' },
        { name: 'mag_right', unicode: '1F50E' },
        { name: 'unlock', unicode: '1F513' },
        { name: 'lock', unicode: '1F512' },
        { name: 'lock_with_ink_pen', unicode: '1F50F' },
        { name: 'closed_lock_with_key', unicode: '1F510' },
        { name: 'key', unicode: '1F511' },
        { name: 'bulb', unicode: '1F4A1' },
        { name: 'flashlight', unicode: '1F526' },
        { name: 'high_brightness', unicode: '1F506' },
        { name: 'low_brightness', unicode: '1F505' },
        { name: 'electric_plug', unicode: '1F50C' },
        { name: 'battery', unicode: '1F50B' },
        { name: 'calling', unicode: '1F4F2' },
        { name: 'email', unicode: '' },
        { name: 'mailbox', unicode: '1F4EB' },
        { name: 'postbox', unicode: '1F4EE' },
        { name: 'bath', unicode: '1F6C0' },
        { name: 'bathtub', unicode: '1F6C1' },
        { name: 'shower', unicode: '1F6BF' },
        { name: 'toilet', unicode: '1F6BD' },
        { name: 'wrench', unicode: '1F527' },
        { name: 'nut_and_bolt', unicode: '1F529' },
        { name: 'hammer', unicode: '1F528' },
        { name: 'seat', unicode: '1F4BA' },
        { name: 'moneybag', unicode: '1F4B0' },
        { name: 'yen', unicode: '1F4B4' },
        { name: 'dollar', unicode: '1F4B5' },
        { name: 'pound', unicode: '1F4B7' },
        { name: 'euro', unicode: '1F4B6' },
        { name: 'credit_card', unicode: '1F4B3' },
        { name: 'money_with_wings', unicode: '1F4B8' },
        { name: 'e-mail', unicode: '1F4E7' },
        { name: 'inbox_tray', unicode: '1F4E5' },
        { name: 'outbox_tray', unicode: '1F4E4' },
        { name: 'envelope', unicode: '2709' },
        { name: 'incoming_envelope', unicode: '1F4E8' },
        { name: 'postal_horn', unicode: '1F4EF' },
        { name: 'mailbox_closed', unicode: '1F4EA' },
        { name: 'mailbox_with_mail', unicode: '1F4EC' },
        { name: 'mailbox_with_no_mail', unicode: '1F4ED' },
        { name: 'door', unicode: '1F6AA' },
        { name: 'smoking', unicode: '1F6AC' },
        { name: 'bomb', unicode: '1F4A3' },
        { name: 'gun', unicode: '1F52B' },
        { name: 'hocho', unicode: '' },
        { name: 'pill', unicode: '1F48A' },
        { name: 'syringe', unicode: '1F489' },
        { name: 'page_facing_up', unicode: '1F4C4' },
        { name: 'page_with_curl', unicode: '1F4C3' },
        { name: 'bookmark_tabs', unicode: '1F4D1' },
        { name: 'bar_chart', unicode: '1F4CA' },
        { name: 'chart_with_upwards_trend', unicode: '1F4C8' },
        { name: 'chart_with_downwards_trend', unicode: '1F4C9' },
        { name: 'scroll', unicode: '1F4DC' },
        { name: 'clipboard', unicode: '1F4CB' },
        { name: 'calendar', unicode: '1F4C6' },
        { name: 'date', unicode: '1F4C5' },
        { name: 'card_index', unicode: '1F4C7' },
        { name: 'file_folder', unicode: '1F4C1' },
        { name: 'open_file_folder', unicode: '1F4C2' },
        { name: 'scissors', unicode: '2702' },
        { name: 'pushpin', unicode: '1F4CC' },
        { name: 'paperclip', unicode: '1F4CE' },
        { name: 'black_nib', unicode: '2712' },
        { name: 'pencil2', unicode: '270F' },
        { name: 'straight_ruler', unicode: '1F4CF' },
        { name: 'triangular_ruler', unicode: '1F4D0' },
        { name: 'closed_book', unicode: '1F4D5' },
        { name: 'green_book', unicode: '1F4D7' },
        { name: 'blue_book', unicode: '1F4D8' },
        { name: 'orange_book', unicode: '1F4D9' },
        { name: 'notebook', unicode: '1F4D3' },
        { name: 'notebook_with_decorative_cover', unicode: '1F4D4' },
        { name: 'ledger', unicode: '1F4D2' },
        { name: 'books', unicode: '1F4DA' },
        { name: 'bookmark', unicode: '1F516' },
        { name: 'name_badge', unicode: '1F4DB' },
        { name: 'microscope', unicode: '1F52C' },
        { name: 'telescope', unicode: '1F52D' },
        { name: 'newspaper', unicode: '1F4F0' },
        { name: 'football', unicode: '1F3C8' },
        { name: 'basketball', unicode: '1F3C0' },
        { name: 'soccer', unicode: '26BD' },
        { name: 'baseball', unicode: '26BE' },
        { name: 'tennis', unicode: '1F3BE' },
        { name: '8ball', unicode: '1F3B1' },
        { name: 'rugby_football', unicode: '1F3C9' },
        { name: 'bowling', unicode: '1F3B3' },
        { name: 'golf', unicode: '26F3' },
        { name: 'mountain_bicyclist', unicode: '1F6B5' },
        { name: 'bicyclist', unicode: '1F6B4' },
        { name: 'horse_racing', unicode: '1F3C7' },
        { name: 'snowboarder', unicode: '1F3C2' },
        { name: 'swimmer', unicode: '1F3CA' },
        { name: 'surfer', unicode: '1F3C4' },
        { name: 'ski', unicode: '1F3BF' },
        { name: 'spades', unicode: '2660' },
        { name: 'hearts', unicode: '2665' },
        { name: 'clubs', unicode: '2663' },
        { name: 'diamonds', unicode: '2666' },
        { name: 'gem', unicode: '1F48E' },
        { name: 'ring', unicode: '1F48D' },
        { name: 'trophy', unicode: '1F3C6' },
        { name: 'musical_score', unicode: '1F3BC' },
        { name: 'musical_keyboard', unicode: '1F3B9' },
        { name: 'violin', unicode: '1F3BB' },
        { name: 'space_invader', unicode: '1F47E' },
        { name: 'video_game', unicode: '1F3AE' },
        { name: 'black_joker', unicode: '1F0CF' },
        { name: 'flower_playing_cards', unicode: '1F3B4' },
        { name: 'game_die', unicode: '1F3B2' },
        { name: 'dart', unicode: '1F3AF' },
        { name: 'mahjong', unicode: '1F004' },
        { name: 'clapper', unicode: '1F3AC' },
        { name: 'memo', unicode: '' },
        { name: 'pencil', unicode: '1F4DD' },
        { name: 'book', unicode: '1F4D6' },
        { name: 'art', unicode: '1F3A8' },
        { name: 'microphone', unicode: '1F3A4' },
        { name: 'headphones', unicode: '1F3A7' },
        { name: 'trumpet', unicode: '1F3BA' },
        { name: 'saxophone', unicode: '1F3B7' },
        { name: 'guitar', unicode: '1F3B8' },
        { name: 'shoe', unicode: '' },
        { name: 'sandal', unicode: '1F461' },
        { name: 'high_heel', unicode: '1F460' },
        { name: 'lipstick', unicode: '1F484' },
        { name: 'boot', unicode: '1F462' },
        { name: 'shirt', unicode: '1F455' },
        { name: 'tshirt', unicode: '' },
        { name: 'necktie', unicode: '1F454' },
        { name: 'womans_clothes', unicode: '1F45A' },
        { name: 'dress', unicode: '1F457' },
        { name: 'running_shirt_with_sash', unicode: '1F3BD' },
        { name: 'jeans', unicode: '1F456' },
        { name: 'kimono', unicode: '1F458' },
        { name: 'bikini', unicode: '1F459' },
        { name: 'ribbon', unicode: '1F380' },
        { name: 'tophat', unicode: '1F3A9' },
        { name: 'crown', unicode: '1F451' },
        { name: 'womans_hat', unicode: '1F452' },
        { name: 'mans_shoe', unicode: '1F45E' },
        { name: 'closed_umbrella', unicode: '1F302' },
        { name: 'briefcase', unicode: '1F4BC' },
        { name: 'handbag', unicode: '1F45C' },
        { name: 'pouch', unicode: '1F45D' },
        { name: 'purse', unicode: '1F45B' },
        { name: 'eyeglasses', unicode: '1F453' },
        { name: 'fishing_pole_and_fish', unicode: '1F3A3' },
        { name: 'coffee', unicode: '2615' },
        { name: 'tea', unicode: '1F375' },
        { name: 'sake', unicode: '1F376' },
        { name: 'baby_bottle', unicode: '1F37C' },
        { name: 'beer', unicode: '1F37A' },
        { name: 'beers', unicode: '1F37B' },
        { name: 'cocktail', unicode: '1F378' },
        { name: 'tropical_drink', unicode: '1F379' },
        { name: 'wine_glass', unicode: '1F377' },
        { name: 'fork_and_knife', unicode: '1F374' },
        { name: 'pizza', unicode: '1F355' },
        { name: 'hamburger', unicode: '1F354' },
        { name: 'fries', unicode: '1F35F' },
        { name: 'poultry_leg', unicode: '1F357' },
        { name: 'meat_on_bone', unicode: '1F356' },
        { name: 'spaghetti', unicode: '1F35D' },
        { name: 'curry', unicode: '1F35B' },
        { name: 'fried_shrimp', unicode: '1F364' },
        { name: 'bento', unicode: '1F371' },
        { name: 'sushi', unicode: '1F363' },
        { name: 'fish_cake', unicode: '1F365' },
        { name: 'rice_ball', unicode: '1F359' },
        { name: 'rice_cracker', unicode: '1F358' },
        { name: 'rice', unicode: '1F35A' },
        { name: 'ramen', unicode: '1F35C' },
        { name: 'stew', unicode: '1F372' },
        { name: 'oden', unicode: '1F362' },
        { name: 'dango', unicode: '1F361' },
        { name: 'egg', unicode: '1F373' },
        { name: 'bread', unicode: '1F35E' },
        { name: 'doughnut', unicode: '1F369' },
        { name: 'custard', unicode: '1F36E' },
        { name: 'icecream', unicode: '1F366' },
        { name: 'ice_cream', unicode: '1F368' },
        { name: 'shaved_ice', unicode: '1F367' },
        { name: 'birthday', unicode: '1F382' },
        { name: 'cake', unicode: '1F370' },
        { name: 'cookie', unicode: '1F36A' },
        { name: 'chocolate_bar', unicode: '1F36B' },
        { name: 'candy', unicode: '1F36C' },
        { name: 'lollipop', unicode: '1F36D' },
        { name: 'honey_pot', unicode: '1F36F' },
        { name: 'apple', unicode: '1F34E' },
        { name: 'green_apple', unicode: '1F34F' },
        { name: 'tangerine', unicode: '1F34A' },
        { name: 'lemon', unicode: '1F34B' },
        { name: 'cherries', unicode: '1F352' },
        { name: 'grapes', unicode: '1F347' },
        { name: 'watermelon', unicode: '1F349' },
        { name: 'strawberry', unicode: '1F353' },
        { name: 'peach', unicode: '1F351' },
        { name: 'melon', unicode: '1F348' },
        { name: 'banana', unicode: '1F34C' },
        { name: 'pear', unicode: '1F350' },
        { name: 'pineapple', unicode: '1F34D' },
        { name: 'sweet_potato', unicode: '1F360' },
        { name: 'eggplant', unicode: '1F346' },
        { name: 'tomato', unicode: '1F345' },
        { name: 'corn', unicode: '1F33D' },
        { name: 'house', unicode: '1F3E0' },
        { name: 'house_with_garden', unicode: '1F3E1' },
        { name: 'school', unicode: '1F3EB' },
        { name: 'office', unicode: '1F3E2' },
        { name: 'post_office', unicode: '1F3E3' },
        { name: 'hospital', unicode: '1F3E5' },
        { name: 'bank', unicode: '1F3E6' },
        { name: 'convenience_store', unicode: '1F3EA' },
        { name: 'love_hotel', unicode: '1F3E9' },
        { name: 'hotel', unicode: '1F3E8' },
        { name: 'wedding', unicode: '1F492' },
        { name: 'church', unicode: '26EA' },
        { name: 'department_store', unicode: '1F3EC' },
        { name: 'european_post_office', unicode: '1F3E4' },
        { name: 'city_sunrise', unicode: '' },
        { name: 'city_sunset', unicode: '1F307' },
        { name: 'japanese_castle', unicode: '1F3EF' },
        { name: 'european_castle', unicode: '1F3F0' },
        { name: 'tent', unicode: '26FA' },
        { name: 'factory', unicode: '1F3ED' },
        { name: 'tokyo_tower', unicode: '1F5FC' },
        { name: 'japan', unicode: '1F5FE' },
        { name: 'mount_fuji', unicode: '1F5FB' },
        { name: 'sunrise_over_mountains', unicode: '1F304' },
        { name: 'sunrise', unicode: '1F305' },
        { name: 'stars', unicode: '1F320' },
        { name: 'statue_of_liberty', unicode: '1F5FD' },
        { name: 'bridge_at_night', unicode: '1F309' },
        { name: 'carousel_horse', unicode: '1F3A0' },
        { name: 'rainbow', unicode: '1F308' },
        { name: 'ferris_wheel', unicode: '1F3A1' },
        { name: 'fountain', unicode: '26F2' },
        { name: 'roller_coaster', unicode: '1F3A2' },
        { name: 'ship', unicode: '1F6A2' },
        { name: 'speedboat', unicode: '1F6A4' },
        { name: 'boat', unicode: '' },
        { name: 'sailboat', unicode: '26F5' },
        { name: 'rowboat', unicode: '1F6A3' },
        { name: 'anchor', unicode: '2693' },
        { name: 'rocket', unicode: '1F680' },
        { name: 'airplane', unicode: '2708' },
        { name: 'helicopter', unicode: '1F681' },
        { name: 'steam_locomotive', unicode: '1F682' },
        { name: 'tram', unicode: '1F68A' },
        { name: 'mountain_railway', unicode: '1F69E' },
        { name: 'bike', unicode: '1F6B2' },
        { name: 'aerial_tramway', unicode: '1F6A1' },
        { name: 'suspension_railway', unicode: '1F69F' },
        { name: 'mountain_cableway', unicode: '1F6A0' },
        { name: 'tractor', unicode: '1F69C' },
        { name: 'blue_car', unicode: '1F699' },
        { name: 'oncoming_automobile', unicode: '1F698' },
        { name: 'car', unicode: '' },
        { name: 'red_car', unicode: '1F697' },
        { name: 'taxi', unicode: '1F695' },
        { name: 'oncoming_taxi', unicode: '1F696' },
        { name: 'articulated_lorry', unicode: '1F69B' },
        { name: 'bus', unicode: '1F68C' },
        { name: 'oncoming_bus', unicode: '1F68D' },
        { name: 'rotating_light', unicode: '1F6A8' },
        { name: 'police_car', unicode: '1F693' },
        { name: 'oncoming_police_car', unicode: '1F694' },
        { name: 'fire_engine', unicode: '1F692' },
        { name: 'ambulance', unicode: '1F691' },
        { name: 'minibus', unicode: '1F690' },
        { name: 'truck', unicode: '1F69A' },
        { name: 'train', unicode: '1F68B' },
        { name: 'station', unicode: '1F689' },
        { name: 'train2', unicode: '1F686' },
        { name: 'bullettrain_front', unicode: '1F685' },
        { name: 'bullettrain_side', unicode: '1F684' },
        { name: 'light_rail', unicode: '1F688' },
        { name: 'monorail', unicode: '1F69D' },
        { name: 'railway_car', unicode: '1F683' },
        { name: 'trolleybus', unicode: '1F68E' },
        { name: 'ticket', unicode: '1F3AB' },
        { name: 'fuelpump', unicode: '26FD' },
        { name: 'vertical_traffic_light', unicode: '1F6A6' },
        { name: 'traffic_light', unicode: '1F6A5' },
        { name: 'warning', unicode: '26A0' },
        { name: 'construction', unicode: '1F6A7' },
        { name: 'beginner', unicode: '1F530' },
        { name: 'atm', unicode: '1F3E7' },
        { name: 'slot_machine', unicode: '1F3B0' },
        { name: 'busstop', unicode: '1F68F' },
        { name: 'barber', unicode: '1F488' },
        { name: 'hotsprings', unicode: '2668' },
        { name: 'checkered_flag', unicode: '1F3C1' },
        { name: 'crossed_flags', unicode: '1F38C' },
        { name: 'izakaya_lantern', unicode: '1F3EE' },
        { name: 'moyai', unicode: '1F5FF' },
        { name: 'circus_tent', unicode: '1F3AA' },
        { name: 'performing_arts', unicode: '1F3AD' },
        { name: 'round_pushpin', unicode: '1F4CD' },
        { name: 'triangular_flag_on_post', unicode: '1F6A9' },
        { name: 'jp', unicode: '1F1EF-1F1F5' },
        { name: 'kr', unicode: '1F1F0-1F1F7' },
        { name: 'cn', unicode: '1F1E8-1F1F3' },
        { name: 'us', unicode: '1F1FA-1F1F8' },
        { name: 'fr', unicode: '1F1EB-1F1F7' },
        { name: 'es', unicode: '1F1EA-1F1F8' },
        { name: 'it', unicode: '1F1EE-1F1F9' },
        { name: 'ru', unicode: '1F1F7-1F1FA' },
        { name: 'gb', unicode: '1F1EC-1F1E7' },
        { name: 'uk', unicode: '' },
        { name: 'de', unicode: '1F1E9-1F1EA' },
        { name: 'one', unicode: '0031-20E3' },
        { name: 'two', unicode: '0032-20E3' },
        { name: 'three', unicode: '0033-20E3' },
        { name: 'four', unicode: '0034-20E3' },
        { name: 'five', unicode: '0035-20E3' },
        { name: 'six', unicode: '0036-20E3' },
        { name: 'seven', unicode: '0037-20E3' },
        { name: 'eight', unicode: '0038-20E3' },
        { name: 'nine', unicode: '0039-20E3' },
        { name: 'keycap_ten', unicode: '1F51F' },
        { name: '1234', unicode: '1F522' },
        { name: 'zero', unicode: '0030-20E3' },
        { name: 'hash', unicode: '0023-20E3' },
        { name: 'symbols', unicode: '1F523' },
        { name: 'arrow_backward', unicode: '25C0' },
        { name: 'arrow_down', unicode: '2B07' },
        { name: 'arrow_forward', unicode: '25B6' },
        { name: 'arrow_left', unicode: '2B05' },
        { name: 'capital_abcd', unicode: '1F520' },
        { name: 'abcd', unicode: '1F521' },
        { name: 'abc', unicode: '1F524' },
        { name: 'arrow_lower_left', unicode: '2199' },
        { name: 'arrow_lower_right', unicode: '2198' },
        { name: 'arrow_right', unicode: '27A1' },
        { name: 'arrow_up', unicode: '2B06' },
        { name: 'arrow_upper_left', unicode: '2196' },
        { name: 'arrow_upper_right', unicode: '2197' },
        { name: 'arrow_double_down', unicode: '23EC' },
        { name: 'arrow_double_up', unicode: '23EB' },
        { name: 'arrow_down_small', unicode: '1F53D' },
        { name: 'arrow_heading_down', unicode: '2935' },
        { name: 'arrow_heading_up', unicode: '2934' },
        { name: 'leftwards_arrow_with_hook', unicode: '21A9' },
        { name: 'arrow_right_hook', unicode: '21AA' },
        { name: 'left_right_arrow', unicode: '2194' },
        { name: 'arrow_up_down', unicode: '2195' },
        { name: 'arrow_up_small', unicode: '1F53C' },
        { name: 'arrows_clockwise', unicode: '1F503' },
        { name: 'arrows_counterclockwise', unicode: '1F504' },
        { name: 'rewind', unicode: '23EA' },
        { name: 'fast_forward', unicode: '23E9' },
        { name: 'information_source', unicode: '2139' },
        { name: 'ok', unicode: '1F197' },
        { name: 'twisted_rightwards_arrows', unicode: '1F500' },
        { name: 'repeat', unicode: '1F501' },
        { name: 'repeat_one', unicode: '1F502' },
        { name: 'new', unicode: '1F195' },
        { name: 'top', unicode: '1F51D' },
        { name: 'up', unicode: '1F199' },
        { name: 'cool', unicode: '1F192' },
        { name: 'free', unicode: '1F193' },
        { name: 'ng', unicode: '1F1F3-1F1EC' },
        { name: 'cinema', unicode: '1F3A6' },
        { name: 'koko', unicode: '1F201' },
        { name: 'signal_strength', unicode: '1F4F6' },
        { name: 'u5272', unicode: '1F239' },
        { name: 'u5408', unicode: '1F234' },
        { name: 'u55b6', unicode: '1F23A' },
        { name: 'u6307', unicode: '1F22F' },
        { name: 'u6708', unicode: '1F237' },
        { name: 'u6709', unicode: '1F236' },
        { name: 'u6e80', unicode: '1F235' },
        { name: 'u7121', unicode: '1F21A' },
        { name: 'u7533', unicode: '1F238' },
        { name: 'u7a7a', unicode: '1F233' },
        { name: 'u7981', unicode: '1F232' },
        { name: 'sa', unicode: '1F1F8-1F1E6' },
        { name: 'restroom', unicode: '1F6BB' },
        { name: 'mens', unicode: '1F6B9' },
        { name: 'womens', unicode: '1F6BA' },
        { name: 'baby_symbol', unicode: '1F6BC' },
        { name: 'no_smoking', unicode: '1F6AD' },
        { name: 'parking', unicode: '1F17F' },
        { name: 'wheelchair', unicode: '267F' },
        { name: 'metro', unicode: '1F687' },
        { name: 'baggage_claim', unicode: '1F6C4' },
        { name: 'accept', unicode: '1F251' },
        { name: 'wc', unicode: '1F6BE' },
        { name: 'potable_water', unicode: '1F6B0' },
        { name: 'put_litter_in_its_place', unicode: '1F6AE' },
        { name: 'secret', unicode: '3299' },
        { name: 'congratulations', unicode: '3297' },
        { name: 'm', unicode: '24C2' },
        { name: 'passport_control', unicode: '1F6C2' },
        { name: 'left_luggage', unicode: '1F6C5' },
        { name: 'customs', unicode: '1F6C3' },
        { name: 'ideograph_advantage', unicode: '1F250' },
        { name: 'cl', unicode: '1F1E8-1F1F1' },
        { name: 'sos', unicode: '1F198' },
        { name: 'id', unicode: '1F1EE-1F1E9' },
        { name: 'no_entry_sign', unicode: '1F6AB' },
        { name: 'underage', unicode: '1F51E' },
        { name: 'no_mobile_phones', unicode: '1F4F5' },
        { name: 'do_not_litter', unicode: '1F6AF' },
        { name: 'non-potable_water', unicode: '1F6B1' },
        { name: 'no_bicycles', unicode: '1F6B3' },
        { name: 'no_pedestrians', unicode: '1F6B7' },
        { name: 'children_crossing', unicode: '1F6B8' },
        { name: 'no_entry', unicode: '26D4' },
        { name: 'eight_spoked_asterisk', unicode: '2733' },
        { name: 'eight_pointed_black_star', unicode: '2734' },
        { name: 'heart_decoration', unicode: '1F49F' },
        { name: 'vs', unicode: '1F19A' },
        { name: 'vibration_mode', unicode: '1F4F3' },
        { name: 'mobile_phone_off', unicode: '1F4F4' },
        { name: 'chart', unicode: '1F4B9' },
        { name: 'currency_exchange', unicode: '1F4B1' },
        { name: 'aries', unicode: '2648' },
        { name: 'taurus', unicode: '2649' },
        { name: 'gemini', unicode: '264A' },
        { name: 'cancer', unicode: '264B' },
        { name: 'leo', unicode: '264C' },
        { name: 'virgo', unicode: '264D' },
        { name: 'libra', unicode: '264E' },
        { name: 'scorpius', unicode: '264F' },
        { name: 'sagittarius', unicode: '2650' },
        { name: 'capricorn', unicode: '2651' },
        { name: 'aquarius', unicode: '2652' },
        { name: 'pisces', unicode: '2653' },
        { name: 'ophiuchus', unicode: '26CE' },
        { name: 'six_pointed_star', unicode: '1F52F' },
        { name: 'negative_squared_cross_mark', unicode: '274E' },
        { name: 'a', unicode: '1F170' },
        { name: 'b', unicode: '1F171' },
        { name: 'ab', unicode: '1F18E' },
        { name: 'o2', unicode: '1F17E' },
        { name: 'diamond_shape_with_a_dot_inside', unicode: '1F4A0' },
        { name: 'recycle', unicode: '267B' },
        { name: 'end', unicode: '1F51A' },
        { name: 'on', unicode: '1F51B' },
        { name: 'soon', unicode: '1F51C' },
        { name: 'clock1', unicode: '1F550' },
        { name: 'clock130', unicode: '1F55C' },
        { name: 'clock10', unicode: '1F559' },
        { name: 'clock1030', unicode: '1F565' },
        { name: 'clock11', unicode: '1F55A' },
        { name: 'clock1130', unicode: '1F566' },
        { name: 'clock12', unicode: '1F55B' },
        { name: 'clock1230', unicode: '1F567' },
        { name: 'clock2', unicode: '1F551' },
        { name: 'clock230', unicode: '1F55D' },
        { name: 'clock3', unicode: '1F552' },
        { name: 'clock330', unicode: '1F55E' },
        { name: 'clock4', unicode: '1F553' },
        { name: 'clock430', unicode: '1F55F' },
        { name: 'clock5', unicode: '1F554' },
        { name: 'clock530', unicode: '1F560' },
        { name: 'clock6', unicode: '1F555' },
        { name: 'clock630', unicode: '1F561' },
        { name: 'clock7', unicode: '1F556' },
        { name: 'clock730', unicode: '1F562' },
        { name: 'clock8', unicode: '1F557' },
        { name: 'clock830', unicode: '1F563' },
        { name: 'clock9', unicode: '1F558' },
        { name: 'clock930', unicode: '1F564' },
        { name: 'heavy_dollar_sign', unicode: '1F4B2' },
        { name: 'copyright', unicode: '00A9' },
        { name: 'registered', unicode: '00AE' },
        { name: 'tm', unicode: '1F1F9-1F1F2' },
        { name: 'x', unicode: '274C' },
        { name: 'heavy_exclamation_mark', unicode: '' },
        { name: 'bangbang', unicode: '203C' },
        { name: 'interrobang', unicode: '2049' },
        { name: 'o', unicode: '2B55' },
        { name: 'heavy_multiplication_x', unicode: '2716' },
        { name: 'heavy_plus_sign', unicode: '2795' },
        { name: 'heavy_minus_sign', unicode: '2796' },
        { name: 'heavy_division_sign', unicode: '2797' },
        { name: 'white_flower', unicode: '1F4AE' },
        { name: '100', unicode: '1F4AF' },
        { name: 'heavy_check_mark', unicode: '2714' },
        { name: 'ballot_box_with_check', unicode: '2611' },
        { name: 'radio_button', unicode: '1F518' },
        { name: 'link', unicode: '1F517' },
        { name: 'curly_loop', unicode: '27B0' },
        { name: 'wavy_dash', unicode: '3030' },
        { name: 'part_alternation_mark', unicode: '303D' },
        { name: 'trident', unicode: '1F531' },
        { name: 'black_square', unicode: '' },
        { name: 'white_square', unicode: '' },
        { name: 'white_check_mark', unicode: '2705' },
        { name: 'black_square_button', unicode: '1F532' },
        { name: 'white_square_button', unicode: '1F533' },
        { name: 'black_circle', unicode: '26AB' },
        { name: 'white_circle', unicode: '26AA' },
        { name: 'red_circle', unicode: '1F534' },
        { name: 'large_blue_circle', unicode: '1F535' },
        { name: 'large_blue_diamond', unicode: '1F537' },
        { name: 'large_orange_diamond', unicode: '1F536' },
        { name: 'small_blue_diamond', unicode: '1F539' },
        { name: 'small_orange_diamond', unicode: '1F538' },
        { name: 'small_red_triangle', unicode: '1F53A' },
        { name: 'small_red_triangle_down', unicode: '1F53B' },
        { name: 'shipit', unicode: '' }]
};
