export const mockArticle: string[] = [
    'Gorem pesum , refert tamen a te dicta, quo modo, Hile Consectetur adipiscing elit. Sed nonne merninisti licere mihi ista probare, quae sunt  dolor sit amet. Evbas  pisum a te ditca, rerert tamen, quo modo. Hile Consectetur adipiscing elit. Lorem ppsum a te dicta? Refert tamen, quo modo. Mihi ista probare, quae sunt  dolor sit amet, consectetur adipiscing elit. Yorem ipsum a te dicta? Refert tamen, quo modo. Refert tamen, qu Hile Consectetur adipiscing elit. Korem fpsum a te dicta? Refert tamen, quo modo adipiscing eli.',
    'Refert tamen a te dicta, quo modo jorem pesum, Hile Consectetur adipiscing elit. Sed nonne merninisti licere mihi ista probare, quae sunt  dolor sit amet. Evbas  pisum a te ditca, rerert tamen, quo modo. Hile Consectetur adipiscing elit. Lorem ppsum a te dicta? Refert tamen, quo modo. Mihi ista probare, quae sunt  dolor sit amet, consectetur adipiscing elit. Yorem ipsum a te dicta? Refert tamen, quo modo. Refert tamen, qu Hile Consectetur adipiscing elit. Korem fpsum a te dicta? Refert tamen, quo modo.',
    'Evbas  pisum a te ditca, rerert tamen, quo modo. Gorem pesum , refert tamen a te dicta, quo modo, Hile Consectetur adipiscing elit. Sed nonne merninisti licere mihi ista probare, quae sunt  dolor sit amet. Hile Consectetur adipiscing elit. Lorem ppsum a te dicta? Refert tamen, quo modo. Mihi ista probare, quae sunt  dolor sit amet, consectetur adipiscing elit. Yorem ipsum a te dicta? Refert tamen, quo modo. Refert tamen, qu Hile Consectetur adipiscing elit. Korem fpsum a te dicta? Refert tamen, quo modo.',
    'Hile Consectetur adipiscing elit. Lorem ppsum a te dicta? Refert tamen, quo modo. Gorem pesum, refert tamen a te dicta, quo modo, Hile Consectetur adipiscing elit. Sed nonne merninisti licere mihi ista probare, quae sunt  dolor sit amet. Evbas  pisum a te ditca, rerert tamen, quo modo adipiscing el. Mihi ista probare, quae sunt  dolor sit amet, consectetur adipiscing elit. Yorem ipsum a te dicta? Refert tamen, quo modo etur adipis. Refert tamen, qu Hile Consectetur adipiscing elit. Korem fpsum a te dicta? Refert tamen, quo modo iscing el.',
    'Mihi ista probare, quae sunt  dolor sit amet, consectetur adipiscing elit. Gorem pesum , refert tamen a te dicta, quo modo, Hile Consectetur adipiscing elit. Sed nonne merninisti licere mihi ista probare, quae sunt  dolor sit amet. Evbas  pisum a te ditca, rerert tamen, quo modo. Hile Consectetur adipiscing elit. Lorem ppsum a te dicta? Refert tamen, quo modo iscing el. Yorem ipsum a te dicta? Refert tamen, quo modo. Refert tamen, qu Hile Consectetur adipiscing elit. Korem fpsum a te dicta? Refert tamen, quo modo  a te dicta?.',
    'Eas pisum a te ditca, rerert tamen, quo modo. Gorem pesum , refert tamen a te dicta, quo modo, Hile Consectetur adipiscing elit. Sed nonne merninisti licere mihi ista probare, quae sunt  dolor sit amet. Hile Consectetur adipiscing elit. Lorem ppsum a te dicta? Refert tamen, quo modo. Mihi ista probare, quae sunt  dolor sit amet, consectetur adipiscing elit. Yorem ipsum a te dicta? Refert tamen, quo modo. Refert tamen, qu Hile Consectetur adipiscing elit. Korem fpsum a te dicta? Refert tamen, quo modo a te dict.',
    'Mihi ista probare, quae sunt  dolor sit amet, consectetur adipiscing elit. Gorem pesum , refert tamen a te dicta, quo modo, Hile Consectetur adipiscing elit. Sed nonne merninisti licere mihi ista probare, quae sunt  dolor sit amet. Evbas  pisum a te ditca, rerert tamen, quo modo. Hile Consectetur adipiscing elit. Lorem ppsum a te dicta? Refert tamen, quo modo. Yorem ipsum a te dicta? Refert tamen, quo modo. Refert tamen, qu Hile Consectetur adipiscing elit. Korem fpsum a te dicta? Refert tamen, quo modo tetur adipisci.',
    'Sed nonne merninisti licere mihi ista probare, quae sunt  dolor sit amet. Evbas  pisum a te ditca, rerert tamen, quo modo. Hile Consectetur adipiscing elit. Lorem ppsum a te dicta? Refert tamen, quo modo. Gorem pesum , refert tamen a te dicta, quo modo, Hile Consectetur adipiscing elit. Mihi ista probare, quae sunt  dolor sit amet, consectetur adipiscing elit. Yorem ipsum a te dicta? Refert tamen, quo modo. Refert tamen, qu Hile Consectetur adipiscing elit. Korem fpsum a te dicta? Refert tamen, quo modo ur adipiscing el.',
    'Hile Consectetur adipiscing elit. Lorem ppsum a te dicta? Refert tamen, quo modo. Gorem pesum, refert tamen a te dicta, quo modo, Hile Consectetur adipiscing elit. Sed nonne merninisti licere mihi ista probare, quae sunt  dolor sit amet. Evbas  pisum a te ditca, rerert tamen, quo modo adipiscing el. Mihi ista probare, quae sunt  dolor sit amet, consectetur adipiscing elit. Yorem ipsum a te dicta? Refert tamen, quo modo etur adipis. Refert tamen, qu Hile Consectetur adipiscing elit. Korem fpsum a te dicta? Refert tamen, quo modo iscing el.',
    'Jahi ista probare, quae sunt  dolor sit amet, consectetur adipiscing elit. Gorem pesum , refert tamen a te dicta, quo modo, Hile Consectetur adipiscing elit. Sed nonne merninisti licere mihi ista probare, quae sunt  dolor sit amet. Evbas  pisum a te ditca, rerert tamen, quo modo. Hile Consectetur adipiscing elit. Lorem ppsum a te dicta? Refert tamen, quo modo iscing el. Yorem ipsum a te dicta? Refert tamen, quo modo. Refert tamen, qu Hile Consectetur adipiscing elit. Korem fpsum a te dicta? Refert tamen, quo modo  a te dicta?',
    'Ibas pisum a te ditca, rerert tamen, quo modo. Gorem pesum , refert tamen a te dicta, quo modo, Hile Consectetur adipiscing elit. Sed nonne merninisti licere mihi ista probare, quae sunt  dolor sit amet. Hile Consectetur adipiscing elit. Lorem ppsum a te dicta? Refert tamen, quo modo. Mihi ista probare, quae sunt  dolor sit amet, consectetur adipiscing elit. Yorem ipsum a te dicta? Refert tamen, quo modo. Refert tamen, qu Hile Consectetur adipiscing elit. Korem fpsum a te dicta? Refert tamen, quo modo a te dict.',
    'Mihi ista probare, quae sunt  dolor sit amet, consectetur adipiscing elit. Gorem pesum , refert tamen a te dicta, quo modo, Hile Consectetur adipiscing elit. Sed nonne merninisti licere mihi ista probare, quae sunt  dolor sit amet. Evbas  pisum a te ditca, rerert tamen, quo modo. Hile Consectetur adipiscing elit. Lorem ppsum a te dicta? Refert tamen, quo modo. Yorem ipsum a te dicta? Refert tamen, quo modo. Refert tamen, qu Hile Consectetur adipiscing elit. Korem fpsum a te dicta? Refert tamen, quo modo tetur adipisci.',
    'Sed nonne merninisti licere mihi ista probare, quae sunt  dolor sit amet. Evbas  pisum a te ditca, rerert tamen, quo modo. Hile Consectetur adipiscing elit. Lorem ppsum a te dicta? Refert tamen, quo modo. Gorem pesum , refert tamen a te dicta, quo modo, Hile Consectetur adipiscing elit. Mihi ista probare, quae sunt  dolor sit amet, consectetur adipiscing elit. Yorem ipsum a te dicta? Refert tamen, quo modo. Refert tamen, qu Hile Consectetur adipiscing elit. Korem fpsum a te dicta? Refert tamen, quo modo ur adipiscing el.'
];
