allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  fsevents: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@docgeni/*'
patchedDependencies:
  '@docgeni/template@2.8.0-next.7': patches/@docgeni__template@2.8.0-next.7.patch
