
name: Feature request
description: Suggest an idea for this project
title: 'TITLE'
labels: ['feature']
body:
  - type: textarea
    attributes:
      label: Feature Description
      placeholder: Provide a brief summary of the feature you would like to see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use Case
      placeholder: Describe the use case(s) that the proposed feature would enable.
    validations:
      required: true